# common
server:
  port: 80
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

--- # dev

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/hotdealmoa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

--- # prod

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://10.41.9.120:3306/hotdealmoa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gktelfahdk