# common
server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  web:
    resources:
      static-locations: classpath:/static/docs

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

--- # dev

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(lHbsII87f/GzFRwsdlZQoVYmIOYu0BEpey6OZ5uaovFkSnFk+hSc9sRyGHTnBE9l)
    username: ENC(1Oyv5OFKC8XKEK8usLmfHQ==)
    password: ENC(Cpt7BnQxchQIZFf95Wy3Bw==)

--- # prod

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ENC(yeTBHVnIbqE94/rebR0nOfCcIk+Adiw/35vU9KeSFNShsRcYJ4ofLi7TOmMDOAgLwO1oFX59UtlQziefCAsB9qZ0LT8Fd8e6t32crAPnu4gGyDLxb1zkhiaCHuYawhVV)
    username: ENC(1Oyv5OFKC8XKEK8usLmfHQ==)
    password: ENC(jSslXA5VwV5JSDGwwOh9QNd5bQcdweKy)