# common
server:
  port: 80
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

--- # dev

spring:
  config:
    activate:
      on-profile: dev

--- # prod

spring:
  config:
    activate:
      on-profile: prod
