# common
server:
  port: 80

spring:
  messages:
    basename: messages
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/docs

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
management:
  endpoints:
    web:
      exposure:
        include: health

--- # dev
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view:
  flyway:
    enabled: false
  datasource:
    url: ENC(lHbsII87f/GzFRwsdlZQoVYmIOYu0BEpey6OZ5uaovFkSnFk+hSc9sRyGHTnBE9l)
    username: ENC(1Oyv5OFKC8XKEK8usLmfHQ==)
    password: ENC(Cpt7BnQxchQIZFf95Wy3Bw==)
  data:
    redis:
      host: ENC(x+3UvWBsumGfAbkOurMW9bTrLR3VMuP9)
      port: 6379

--- # prod

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: ENC(gOmAwTYpg3dU8af2vBbSS7hWd1Sh3kU7UQRtC7eCV2u4YuG6N6tGr2vkKAgo3Wg+cjbNCDmLW9u7629xz/uwq/3jUcXAr9sfqKkXr2TFIgIR4JF1Naxdr7lsyfeS9r/V)
    username: ENC(1Oyv5OFKC8XKEK8usLmfHQ==)
    password: ENC(AKzU/04JNA3zOyx5zhdWEo/YI/JNVt5ZZGrc02XBtAU=)
  data:
    redis:
      host: ENC(JJHIkdDgJ//eH3+hvJmU1l1lTXs94Ujx)
      port: 6379