# common
server:
  port: 80
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

--- # dev

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/hotdealmoa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

--- # prod

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://118.67.129.227:3306/hotdealmoa?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password: