= Hot-deal-moa API guide
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== Member

=== 회원 가입 성공

operation::member-controller-test/join_success[snippets='request-fields,http-request,response-fields,http-response']

=== 회원 가입 실패

operation::member-controller-test/join_fail[snippets='request-fields,http-request,response-fields,http-response']

==== 사용 가능한 이메일

operation::member-controller-test/email_not-exists[snippets='query-parameters,http-request,response-fields,http-response']

==== 이미 사용중 인 이메일

operation::member-controller-test/email_exists[snippets='query-parameters,http-request,response-fields,http-response']

=== 로그인 성공

operation::member-controller-test/login_success[snippets='request-fields,http-request,response-fields,http-response']

=== 로그인 실패

operation::member-controller-test/login_fail[snippets='request-fields,http-request,response-fields,http-response']

=== 로그 아웃

operation::member-controller-test/logout[snippets='http-request,response-fields,http-response']

=== 회원 상세 정보 가져오기

operation::member-controller-test/get-profile[snippets='http-request,response-fields,http-response']

=== 회원 정보 수정

operation::member-controller-test/update_profile[snippets='request-fields,http-request,response-fields,http-response']

=== 패스워드 변경 성공

operation::member-controller-test/change_password_success[snippets='request-fields,http-request,response-fields,http-response']

=== 패스워드 변경 실패

operation::member-controller-test/change_password_fail[snippets='request-fields,http-request,response-fields,http-response']

== Product

=== 상품 리스트 조회

operation::product-controller-test/get-product-list[snippets='query-parameters,http-request,response-fields,http-response']

=== 상품 상세 조회

operation::product-controller-test/get-product-detail[snippets='path-parameters,http-request,response-fields,http-response']

=== 상품 등록

operation::product-controller-test/regi-product[snippets='request-fields,http-request,response-fields,http-response']

=== 상품 수정

operation::product-controller-test/update-product[snippets='path-parameters,http-request,response-fields,http-response']

=== 상품 삭제

operation::product-controller-test/delete-product[snippets='path-parameters,http-request,response-fields,http-response']

== Review

=== 리뷰 조회

operation::review-test-controller-test/get-review-list[snippets='query-parameters,http-request,response-fields,http-response']

=== 리뷰 등록

operation::review-test-controller-test/create-review[snippets='request-fields,http-request,response-fields,http-response']

=== 리뷰 업데이트

operation::review-test-controller-test/update-review[snippets='path-parameters,request-fields,http-request,response-fields,http-response']

=== 리뷰 삭제

operation::review-test-controller-test/delete-review[snippets='path-parameters,http-request,http-response']

== Coupon

=== 쿠폰 리스트 조회

operation::coupon-controller-test/get-coupon-list[snippets='query-parameters,http-request,response-fields,http-response']


== Order

=== 결제 전 주문 정보

operation::order-controller-test/get-order-info[snippets='query-parameters,http-request,response-fields,http-response']

=== 주문 상세 정보

operation::order-controller-test/get-order-detail-info[snippets='path-parameters,http-request,response-fields,http-response']

=== 주문 리스트

operation::order-controller-test/get-order-list[snippets='http-request,response-fields,http-response']

=== 주문 진행 성공

operation::order-controller-test/create-order-success[snippets='request-fields,http-request,response-fields,http-response']

=== 주문 진행 실패

operation::order-controller-test/create-order-fail[snippets='request-fields,http-request,response-fields,http-response']

=== 주문 상태 정보 업데이트

operation::order-controller-test/update-order-status[snippets='path-parameters,request-fields,http-request,response-fields,http-response']