name: CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3
      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 권한 부여
        run: chmod +x gradlew
        shell: bash

      - name: dev 환경에서 Gradle test 수행
        if: contains(github.ref, 'develop')
        run: ./gradlew clean test
        shell: bash

      - name: Gradle build 수행
        run: ./gradlew build -x test
        shell: bash

      - name: 서버로 Jar파일 복사
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_SERVERS }}
          username: ${{ secrets.NCP_SERVER_USER }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: ${{ secrets.NCP_SERVERS_PORT }}
          source: "./build/libs/*.jar, ./deploy.sh"
          target: "/hotdealmoa"
