name: Java CI with Gradle

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3
      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Gradle 권한 부여
        run: chmod +x gradlew
        shell: bash

      - name: Gradle build 수행
        run: ./gradlew build -x test
        shell: bash

      - name: local 환경에서 Gradle test 수행
        run: SPRING_PROFILES_ACTIVE=[local] ./gradlew clean test
        shell: bash
        
      - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트를 등록합니다.
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}